
name: Willow Application Server
version: 0.2.0
slug: willow_application_server
description: A Willow Application Server instance running in Home Assistant
url: https://github.com/nwithan8/hassio-addons/tree/master/willow-application-server
codenotary: nwithan8@users.noreply.github.com
init: false
arch:
  - aarch64
  - amd64
apparmor: true
panel_icon: mdi:server-network
host_network: true
webui: http://[HOST]:[PORT:8502]
map:
 - addon_config:rw
